modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/refinedmods/refinedstorageaddons"
[[mods]]
modId="refinedstorageaddons"
version="${version}"
displayName="Refined Storage Addons"
authors="Refined Mods"
description='''
An addon mod for Refined Storage
'''
[[dependencies.refinedstorageaddons]]
    modId="refinedstorage"
    versionRange="[1.8.1,)"
    mandatory=true
    ordering="AFTER"
    side="BOTH"