modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/refinedmods/refinedstorageaddons"
[[mods]]
modId="refinedstorageaddons"
version="${version}"
displayName="Refined Storage Addons"
updateJSONURL="https://refinedmods.com/refined-storage-addons/update.json"
displayURL="https://refinedmods.com/refined-storage-addons"
authors="Refined Mods"
description='''
An addon mod for Refined Storage
'''
[[dependencies.refinedstorageaddons]]
    modId="refinedstorage"
    versionRange="[1.9.1,)"
    mandatory=true
    ordering="AFTER"
    side="BOTH"