modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/raoulvdberge/refinedstorageaddons"
[[mods]]
modId="refinedstorageaddons"
version="${version}"
displayName="Refined Storage Addons"
authors="Refined Storage Addons contributors"
description='''
An addon mod for Refined Storage
'''
[[dependencies.refinedstorageaddons]]
    modId="refinedstorage"
    versionRange="[1.7.1,)"
    mandatory=true
    ordering="AFTER"
    side="BOTH"